DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS companies;
CREATE TABLE companies (
  id SERIAL PRIMARY KEY,
  company_name VARCHAR(30),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE employees (
  id SERIAL PRIMARY KEY,
  employee VARCHAR(120) NOT NULL,
  post VARCHAR(100) NOT NULL,
  company_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE payments (
  id SERIAL PRIMARY KEY,
  date_of DATE NOT NULL,
  total INT NOT NULL,
  employee_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE ON UPDATE CASCADE
);